### ISSUE TITLE
react icon is not working due to icon package file Ri and Ti

### ISSUE THREAD

**Issue by Amankumarpatel123** [briancodex/react-todo-app-v1#3]
instead of using ricloseCircleLine and Tiedit alternative but can be used to terminate the error
import { AiFillCloseCircle } from 'react-icons/ai';
import { RiFileEditLine } from 'react-icons/ri';

<AiFillCloseCircle/>
<RiFileEditLine/>

**Comment by walid885** [comment]
error while trying to go through the todo.map : 
error message : ToDo.js:24 Uncaught TypeError: todos.map is not a function
    at ToDo 
any solution to this problem ? ,
